apiVersion: v1
data:
  GATEWAY_HOST: http://apigateway:8080
  KAFKA_ADDRESS: kafkaa:9092
  KAFKA_GROUP_ID: '"1"'
  KAFKA_PROCESS_TOPIC: process
  KAFKA_PROCESSED_TOPIC: processed
  MONGO_DBNAME: admin
  MONGO_HOST: mongodb
  VIDEOPROCESSING_HOST: http://vps:5000
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"vms-env-file","creationTimestamp":null},"data":{"GATEWAY_HOST":"http://apigateway:8080","KAFKA_ADDRESS":"kafkaa:9092","KAFKA_GROUP_ID":"\"1\"","KAFKA_PROCESSED_TOPIC":"processed","KAFKA_PROCESS_TOPIC":"process","MONGO_DBNAME":"admin","MONGO_HOST":"mongodb","VIDEOPROCESSING_HOST":"http://vps:5000"}}
  creationTimestamp: "2020-01-28T17:57:21Z"
  name: vms-env-file
  namespace: default
  resourceVersion: "211479"
  selfLink: /api/v1/namespaces/default/configmaps/vms-env-file
  uid: a878f4af-e4cd-4006-ab3b-eef19fa745f3
