apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaa:9092
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"alertmanagement-env-file","creationTimestamp":null},"data":{"KAFKA_ADDRESS":"kafkaa:9092"}}
  creationTimestamp: "2020-01-28T17:57:21Z"
  name: alertmanagement-env-file
  namespace: default
  resourceVersion: "211482"
  selfLink: /api/v1/namespaces/default/configmaps/alertmanagement-env-file
  uid: d3c56e2a-0618-4958-9886-2cf90c4eb407
