
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
spec:
  selector:
    matchLabels:
      app: spark_pod
  replicas: 1
  template:
    metadata:
      labels:
        app: spark_pod
    spec:
     containers:
     - name: spark
       image: spark:v1
       ports:
       - containerPort: 7077
       command: [" cd .."]
       command: ["./sbin/start-all.sh"]
       imagePullPolicy: Never
     
