apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    svc: spark
spec:
  type: LoadBalancer
  ports:
  - port: 7077
    targetPort: 7077
    protocol: TCP
    name: spark
  selector:
    app: spark_pod


