
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: apigateway_pod
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway_pod
    spec:
     volumes:
     - name: prometheus
       hostPath:
         path: /storage/prometheus/prometheus.yml
         type: File
         
     - name: videos
       hostPath:
         path: /storage/videofiles
         type: Directory
     containers:
     - name: prometheus
       image: prom/prometheus:latest
       volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus
       ports:
       - containerPort: 9090
     - name: apigateway
       image: apigateway:v1
       resources:
        limits:
         memory: "800Mi"
        requests:
         memory: "600Mi"
       volumeMounts:
         - mountPath: /app/videofiles
           name: videos
       envFrom:
        - configMapRef:
            name: apigateway-env-file
       
       ports:
       - containerPort: 8080
       imagePullPolicy: Never
     
