apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaa:9092
  KAFKA_GROUP_ID: '"1"'
  KAFKA_PROCESS_TOPIC: process
  KAFKA_PROCESSED_TOPIC: processed
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"vps-env-file","creationTimestamp":null},"data":{"KAFKA_ADDRESS":"kafkaa:9092","KAFKA_GROUP_ID":"\"1\"","KAFKA_PROCESSED_TOPIC":"processed","KAFKA_PROCESS_TOPIC":"process"}}
  creationTimestamp: "2020-01-28T17:57:21Z"
  name: vps-env-file
  namespace: default
  resourceVersion: "211480"
  selfLink: /api/v1/namespaces/default/configmaps/vps-env-file
  uid: f236ff07-415b-476f-953f-55db2e7b94c5
