apiVersion: v1
data:
  VMS_HOST: http://vms:8080
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"apigateway-env-file","creationTimestamp":null},"data":{"VMS_HOST":"http://vms:8080"}}
  creationTimestamp: "2020-01-28T17:57:21Z"
  name: apigateway-env-file
  namespace: default
  resourceVersion: "211481"
  selfLink: /api/v1/namespaces/default/configmaps/apigateway-env-file
  uid: fdcb40cc-c3cd-4604-b214-dbee86b21873
