apiVersion: v1
data:
  MONGO_ROOT_PASSWORD: YWRtaW4=
  MONGO_ROOT_USERNAME: YWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"vms-secret-file","creationTimestamp":null},"data":{"MONGO_ROOT_PASSWORD":"YWRtaW4=","MONGO_ROOT_USERNAME":"YWRtaW4="}}
  creationTimestamp: "2020-01-28T17:44:06Z"
  name: vms-secret-file
  namespace: default
  resourceVersion: "209334"
  selfLink: /api/v1/namespaces/default/secrets/vms-secret-file
  uid: 05d7c9dc-0249-4617-87d1-af69ac4dda3e
type: Opaque
