
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
spec:
  selector:
    matchLabels:
      app: alert_pod
  replicas: 1
  template:
    metadata:
      labels:
        app: alert_pod
    spec:
     containers:
     - name: alert
       image: alert:v1
       env:
       - name: KAFKA_ADDRESS
         value: kafkaa:9092
       ports:
       - containerPort: 8080
       imagePullPolicy: Never
