apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"mongodb-secret-file","creationTimestamp":null},"data":{"MONGO_INITDB_ROOT_PASSWORD":"YWRtaW4=","MONGO_INITDB_ROOT_USERNAME":"YWRtaW4="}}
  creationTimestamp: "2020-01-28T17:44:07Z"
  name: mongodb-secret-file
  namespace: default
  resourceVersion: "209343"
  selfLink: /api/v1/namespaces/default/secrets/mongodb-secret-file
  uid: 2926c2a3-dcf1-44f8-85f1-bb717527ad9d
type: Opaque
